### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by hank** [tsheets/api_python#5]
I recently started using this and found that all the imports are relative and will only work in Python 2. I went through the library and changed all the imports to be relative for my own personal use, but it would be good for the maintainer of this repo to 2to3 the entire library for general use. If for some reason this isn't something that can be done, I might go ahead and do the work at some point, but it's definitely not on my short list. Thanks for providing this - it saved me a lot of time.

**Comment by daveschaefer** [comment]
I created a pull request for this in #6

**Comment by dustinsweet** [comment]
Thanks to Dave, Python 3 is now available.
